### PR TITLE
chore: upgrade nx to 14.8.4

### PR DESCRIPTION
**Pull request by cogwirrel**
For https://github.com/advisories/GHSA-cph5-m8f7-6c5x via https://github.com/nrwl/nx/pull/12437

### CODE REVIEW

**Review by mteichtahl — APPROVED** [review]
nice quick and simple ver bump.

**Comment by martenpayne** [comment]
:+1: looks good

**Comment by JeremyJonas** [comment]
@cogwirrel Given these files are managed by **projen**, shouldn't this be defined in **PDKMonorepoProject** project file?

Either via `devDeps` or `resolveDependencies`...
1. [PDKMonorepoProject `devDeps`](https://github.com/aws/aws-prototyping-sdk/blob/e5571bbf476bb86373cfe6512552362a99b53564/private/projects/pdk-monorepo-project.ts#L44)
2. [PDKMonorepoProject `resolveDependendencies`](https://github.com/aws/aws-prototyping-sdk/blob/e5571bbf476bb86373cfe6512552362a99b53564/private/projects/pdk-monorepo-project.ts#L251-L268)

**Comment by cogwirrel** [comment]
> @cogwirrel Given these files are managed by **projen**, shouldn't this be defined in **PDKMonorepoProject** project file?
> 
> Either via `devDeps` or `resolveDependencies`...
> 
> 1. [PDKMonorepoProject `devDeps`](https://github.com/aws/aws-prototyping-sdk/blob/e5571bbf476bb86373cfe6512552362a99b53564/private/projects/pdk-monorepo-project.ts#L44)
> 2. [PDKMonorepoProject `resolveDependendencies`](https://github.com/aws/aws-prototyping-sdk/blob/e5571bbf476bb86373cfe6512552362a99b53564/private/projects/pdk-monorepo-project.ts#L251-L268)

The specific versions don't need to be hardcoded in the .projenrc :) https://projen.io/node.html#dependencies 

> Any dependencies without specific version ranges set (such as react or react@*) will given a version range in package.json so that future package upgrades and changes to the generated lockfiles such as package-lock.json or yarn.lock will follow semver.

Basically if you don't hardcode a version in projenrc you're then free to use other tooling like dependabot or `npm-check-updates` etc for managing your dependency versions via the package.json :)

I actually used some of the steps from the built in [`upgrade-deps` task from the monorepo project](https://github.com/aws/aws-prototyping-sdk/blob/e5571bbf476bb86373cfe6512552362a99b53564/packages/nx-monorepo/src/nx-monorepo.ts#L263-L281) to upgrade these dependencies (`npx projen upgrade-deps`). Though in this case I just wanted to target the nx deps specifically so ran `npx npm-check-updates --deep --rejectVersion 0.0.0 -u "@nrwl/*" "nx"` :)

**Pull request merged**
