### PR TITLE
feat(monorepo-ts): upgrade syncpack to v12

### LINKED ISSUE #675: [BUG] (monorepo) upgrade-deps using outdated syncpack (error)
### Describe the bug

```
Your syncpack config file contains values deprecated in https://github.com/JamieMason/syncpack/releases/tag/9.0.0
  Dependency Types: dev,overrides,peer,pnpmOverrides,prod,resolutions
  Docs: https://jamiemason.github.io/syncpack/config/dependency-types
```

### Expected Behavior

To upgrade the monorepo's dependencies.

### Current Behavior

Throws error in description.

### Reproduction Steps

This should be happening in all new PDK monorepos, it would seem, but here is the syncpack file:

```
{
  "dependencyTypes": [],
  "dev": true,
  "filter": ".",
  "indent": "  ",
  "overrides": true,
  "peer": true,
  "pnpmOverrides": true,
  "prod": true,
  "resolutions": true,
  "workspace": true,
  "semverGroups": [],
  "semverRange": "",
  "sortAz": [
    "contributors",
    "dependencies",
    "devDependencies",
    "keywords",
    "peerDependencies",
    "resolutions",
    "scripts"
  ],
  "sortFirst": [
    "name",
    "description",
    "version",
    "author"
  ],
  "source": [],
  "versionGroups": [],
  "//": "~~ Generated by projen. To modify, edit .projenrc.ts and run \"pnpm exec projen\"."
}
```

"syncpack": "^12.3.0",

### Possible Solution

Workaround: Downgrade `syncpack` 4 major versions to `^8`.  You must use `addDevDeps` or the PDK overwrites your version.

### Additional Information/Context

_No response_

### PDK version used

0.22.48

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Ubuntu 22.04

### PR DESCRIPTION
**Pull request by cogwirrel**
Upgrade from Syncpack v8 to v12. Additionally pin syncpack to major version 12 to avoid any future
breaking changes in new major versions from affecting new projects.

Note that unfortunately the Syncpack exported `RcFile` types are not built with JSII so we must redefine them in `syncpack-options.ts`

BREAKING CHANGE: Syncpack configuration for monorepo updated with breaking changes aligned with
Syncpack upgrade from v8 to v12:

- The `dev`, `overrides`, `peer`, `pnpmOverrides`, `prod`, `resolutions` and `workspace` boolean
flags are replaced by the `dependencyTypes` array.
- The `workspace` dependency type is now named `local`. 
- `semverRange` is deprecated in favour of adding a range to `semverGroups`

For more details, please refer to the Syncpack releases between 8 and 12:
- [Syncpack v9](https://github.com/JamieMason/syncpack/releases/tag/9.0.0)
- [Syncpack v10](https://github.com/JamieMason/syncpack/releases/tag/10.0.0)
- [Syncpack v11](https://github.com/JamieMason/syncpack/releases/tag/11.0.0)
- [Syncpack v12](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0)

Additionally Syncpack related types and configs are namespaced under a `Syncpack` namespace,
eg. `Syncpack.DEFAULT_CONFIG` for the default monorepo syncpack config.

Fixes #675, #553

### CODE REVIEW

**Comment by cogwirrel** [comment]
@JamieMason would love it if you could take a look at this too if you have time to double check I haven't done anything crazy!

**Comment by JamieMason** [comment]
Looks good @cogwirrel, you've added `!local` which is the main thing that people don't handle and trips them up.

I think there's probably a way to have to redeclare less of Syncpack's types, maybe by importing some of them from [`/src/config/types.ts`](https://github.com/JamieMason/syncpack/blob/db2b31ccdb1a28fdbe0c42d27ce956ea5c6c543a/src/config/types.ts) – none of those use `Partial`, only [`/src/index.ts`](https://github.com/JamieMason/syncpack/blob/db2b31ccdb1a28fdbe0c42d27ce956ea5c6c543a/src/index.ts#L3) when it re-exports it, if that helps at all.

**Comment by cogwirrel** [comment]
> Looks good @cogwirrel, you've added `!local` which is the main thing that people don't handle and trips them up.
> 
> I think there's probably a way to have to redeclare less of Syncpack's types, maybe by importing some of them from [`/src/config/types.ts`](https://github.com/JamieMason/syncpack/blob/db2b31ccdb1a28fdbe0c42d27ce956ea5c6c543a/src/config/types.ts) – none of those use `Partial`, only [`/src/index.ts`](https://github.com/JamieMason/syncpack/blob/db2b31ccdb1a28fdbe0c42d27ce956ea5c6c543a/src/index.ts#L3) when it re-exports it, if that helps at all.

Thanks so much for looking!

I had a quick play with importing other types but I think they need to be defined in a JSII project to reuse them unfortunately - the `Partial` error was just the first hurdle!

**Review by agdimech — APPROVED** [review]
Fantastic work! Thanks for updating this and thanks to @JamieMason for your input :)

**Comment by JamieMason** [comment]
Hey @cogwirrel, I had a look at trying to [upgrade to v14 in this fork](https://github.com/aws/aws-pdk/compare/mainline...JamieMason:aws-pdk:syncpack?expand=1#diff-dc3a048422937e4ece592ca654d2b32df0676e206b0bc7012e6b128795081bfa). 

I got reasonably far but it'll take someone that knows this project to decide whether the versions listed below should have a `^` or be exact, whether peerDependencies should be handled differently etc.

You may not need or want to upgrade, but I'll leave the fork there for a while incase it helps.

<details><summary>Output of syncpack lint</summary>

```
[] ~/Dev/aws-pdk <syncpack> syncpack lint
= Default Version Group ========================================================
   5x @aws-cdk/aws-cognito-identitypool-alpha
      ✘ latest → latest in package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^2.163.1-alpha.0 → latest in packages/identity/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^2.163.1-alpha.0 → latest in packages/identity/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^2.163.1-alpha.0 → latest in packages/pdk/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^2.163.1-alpha.0 → latest in packages/pdk/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
   4x @aws/aws-arch
      ✘ ^0.x → 0.0.0 in packages/cdk-graph-plugin-diagram/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/cdk-graph-plugin-threat-composer/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
   4x @aws/cdk-graph
      ✘ ^0.x → 0.0.0 in packages/cdk-graph-plugin-diagram/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/cdk-graph-plugin-threat-composer/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
  10x @aws/monorepo
      ✘ ^0.x → 0.0.0 in packages/cdk-graph/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/cloudscape-react-ts-website/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/identity/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/infrastructure/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/infrastructure/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/pdk-nag/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/static-website/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/type-safe-api/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/type-safe-api/package.json at .dependencies (DiffersToHighestOrLowestSemver)
   1x @aws/pdk
      ✘ ^0 → 0 in package.json at .devDependencies (SemverRangeMismatch)
   7x @aws/pdk-nag
      ✘ ^0.x → 0.0.0 in packages/cdk-graph/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/cdk-graph-plugin-threat-composer/package.json at .peerDependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/identity/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/pipeline/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/static-website/package.json at .dependencies (DiffersToHighestOrLowestSemver)
      ✘ ^0.x → 0.0.0 in packages/type-safe-api/package.json at .dependencies (DiffersToHighestOrLowestSemver)
   2x @aws/pipeline
      ✘ ^0.x → 0.0.0 in packages/cdk-graph/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
   1x @pnpm/types
      ✘ ^9.0.0 → 9.0.0 in package.json at .dependencies (SemverRangeMismatch)
   7x @types/fs-extra
      ✘ 9.0.13 → 11.0.4 in packages/aws-arch/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
  15x @types/node
      ✘ ^18 → 18 in packages/aws-arch/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/cdk-graph/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/cdk-graph-plugin-diagram/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/cdk-graph-plugin-threat-composer/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/cloudscape-react-ts-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in docs/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/identity/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/infrastructure/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/monorepo/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/pdk/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/pdk-nag/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/pipeline/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/static-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^18 → 18 in packages/type-safe-api/package.json at .devDependencies (SemverRangeMismatch)
  15x @typescript-eslint/eslint-plugin
      ✘ ^7 → 7 in packages/aws-arch/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cdk-graph/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cdk-graph-plugin-diagram/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cdk-graph-plugin-threat-composer/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cloudscape-react-ts-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in docs/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/identity/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/infrastructure/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/monorepo/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/pdk/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/pdk-nag/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/pipeline/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/static-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/type-safe-api/package.json at .devDependencies (SemverRangeMismatch)
  15x @typescript-eslint/parser
      ✘ ^7 → 7 in packages/aws-arch/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cdk-graph/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cdk-graph-plugin-diagram/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cdk-graph-plugin-threat-composer/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/cloudscape-react-ts-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in docs/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/identity/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/infrastructure/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/monorepo/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/pdk/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/pdk-nag/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/pipeline/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/static-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^7 → 7 in packages/type-safe-api/package.json at .devDependencies (SemverRangeMismatch)
  19x aws-cdk-lib
      ✘ ^2.163.1 → 2.163.1 in packages/cdk-graph/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/cdk-graph-plugin-diagram/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/cdk-graph-plugin-threat-composer/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/identity/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/pdk/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/pdk-nag/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/pipeline/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/static-website/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.163.1 → 2.163.1 in packages/type-safe-api/package.json at .peerDependencies (SemverRangeMismatch)
  16x cdk-nag
      ✘ ^2.31.0 → 2.31.0 in packages/cdk-graph-plugin-threat-composer/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.31.0 → 2.31.0 in packages/identity/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.31.0 → 2.31.0 in packages/pdk/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.31.0 → 2.31.0 in packages/pdk-nag/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.31.0 → 2.31.0 in packages/pipeline/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.31.0 → 2.31.0 in packages/static-website/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^2.31.0 → 2.31.0 in packages/type-safe-api/package.json at .peerDependencies (SemverRangeMismatch)
  27x constructs
      ✘ ^10.4.2 → 10.4.2 in packages/aws-arch/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/cdk-graph/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/cdk-graph-plugin-diagram/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/cdk-graph-plugin-threat-composer/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/cloudscape-react-ts-website/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/identity/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/infrastructure/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/monorepo/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/pdk/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/pdk-nag/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/pipeline/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/static-website/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.4.2 → 10.4.2 in packages/type-safe-api/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^10.0.0 → 10.4.2 in package.json at .devDependencies (DiffersToHighestOrLowestSemver)
  15x eslint
      ✘ ^8 → 8 in packages/aws-arch/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/cdk-graph/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/cdk-graph-plugin-diagram/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/cdk-graph-plugin-threat-composer/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/cloudscape-react-ts-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in docs/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/identity/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/infrastructure/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/monorepo/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/pdk/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/pdk-nag/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/pipeline/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/static-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^8 → 8 in packages/type-safe-api/package.json at .devDependencies (SemverRangeMismatch)
   1x got
      ✘ ^11.8.5 → 11.8.5 in package.json at .devDependencies (SemverRangeMismatch)
  13x jest-junit
      ✘ ^15 → 15 in packages/aws-arch/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/cdk-graph/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/cdk-graph-plugin-diagram/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/cdk-graph-plugin-threat-composer/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/cloudscape-react-ts-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/identity/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/infrastructure/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/monorepo/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/pdk/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/pdk-nag/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/pipeline/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/static-website/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^15 → 15 in packages/type-safe-api/package.json at .devDependencies (SemverRangeMismatch)
   2x node-fetch
      ✘ ^2.6.7 → 2.6.7 in packages/aws-arch/package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^2.6.7 → 2.6.7 in packages/pdk/package.json at .devDependencies (SemverRangeMismatch)
   4x nx
      ✘ ^19 → 19 in package.json at .peerDependencies (SemverRangeMismatch)
      ✘ 19.8.14 → 19 in packages/monorepo/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
      ✘ 19.8.14 → 19 in packages/pdk/package.json at .devDependencies (DiffersToHighestOrLowestSemver)
      ✘ 19.0.0 → 19 in package.json at .devDependencies (DiffersToHighestOrLowestSemver)
  26x projen
      ✘ ^0.82.8 → 0.82.8 in packages/aws-arch/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/cdk-graph/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/cdk-graph-plugin-diagram/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/cdk-graph-plugin-threat-composer/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/cloudscape-react-ts-website/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/identity/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/infrastructure/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/monorepo/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/pdk/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in package.json at .devDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/pipeline/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/static-website/package.json at .peerDependencies (SemverRangeMismatch)
      ✘ ^0.82.8 → 0.82.8 in packages/type-safe-api/package.json at .peerDependencies (SemverRangeMismatch)
   1x syncpack
      ✘ ^14 → 14 in package.json at .devDependencies (SemverRangeMismatch)
   1x tar
      ✘ ^4.4.18 → 4.4.18 in package.json at .pnpm.overrides (SemverRangeMismatch)
   1x wrap-ansi
      ✘ ^7.0.0 → 7.0.0 in package.json at .pnpm.overrides (SemverRangeMismatch)
[] ~/Dev/aws-pdk <syncpack>
```

</details>

https://syncpack.dev/guide/migrate-v14/

**Pull request merged**
