### PR TITLE
fix(pdk-monorepo): pin syncpack dependency to stay compatible to NodeJS v18

### LINKED ISSUE #823: [BUG] @aws/pdk (monorepo) is incompatible with NodeJs <20 due to transient syncpack..minimatch dependency
### Describe the bug

Running `npx projen new --from @aws/pdk monorepo-ts` in Node environments <20 will give the following error, due to [minimatch from version 10](https://github.com/isaacs/minimatch/blob/main/changelog.md#100), which was intriduced by [syncpack in Version 12.4.0](https://github.com/JamieMason/syncpack/releases/tag/13.0.0):

```
error minimatch@10.0.1: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.20.4"
error Found incompatible module.
```

### Expected Behavior

I can create a new project (or use an existing project) with the default Node version (18) that projen is using.

### Current Behavior

```shell
$ npx projen new --from @aws/pdk monorepo-ts
/home/bgenz-ep/Projects/bweigel/projen-weird-error
└── (empty)


added 2 packages in 2s

10 packages are looking for funding
  run `npm fund` for details
👾 installing module @aws/pdk...

added 7 packages, and audited 344 packages in 11s

97 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

👾 Installing dependencies...
👾 install | yarn install --check-files
yarn install v1.22.14
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @aws/pdk > @pnpm/reviewing.dependencies-hierarchy > @pnpm/lockfile-file > @zkochan/rimraf > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @aws/pdk > @pnpm/reviewing.dependencies-hierarchy > @pnpm/lockfile-file > @zkochan/rimraf > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @aws/pdk > @pnpm/reviewing.dependencies-hierarchy > @pnpm/lockfile-file > @zkochan/rimraf > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning eslint > @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
warning projen > glob@8.1.0: Glob versions prior to v9 are no longer supported
warning projen > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning projen > shx > shelljs > glob@7.2.3: Glob versions prior to v9 are no longer supported
[3/5] Fetching packages...
info @nx/nx-darwin-x64@19.0.0: The platform "linux" is incompatible with this module.
info "@nx/nx-darwin-x64@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nx/nx-darwin-arm64@19.0.0: The platform "linux" is incompatible with this module.
info "@nx/nx-darwin-arm64@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nx/nx-darwin-arm64@19.0.0: The CPU architecture "x64" is incompatible with this module.
info @nx/nx-freebsd-x64@19.0.0: The platform "linux" is incompatible with this module.
info "@nx/nx-freebsd-x64@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nx/nx-win32-x64-msvc@19.0.0: The platform "linux" is incompatible with this module.
info "@nx/nx-win32-x64-msvc@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nx/nx-linux-arm64-gnu@19.0.0: The CPU architecture "x64" is incompatible with this module.
info "@nx/nx-linux-arm64-gnu@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nx/nx-linux-arm64-musl@19.0.0: The CPU architecture "x64" is incompatible with this module.
info "@nx/nx-linux-arm64-musl@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nx/nx-win32-arm64-msvc@19.0.0: The platform "linux" is incompatible with this module.
info "@nx/nx-win32-arm64-msvc@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nx/nx-win32-arm64-msvc@19.0.0: The CPU architecture "x64" is incompatible with this module.
info @nx/nx-linux-arm-gnueabihf@19.0.0: The CPU architecture "x64" is incompatible with this module.
info "@nx/nx-linux-arm-gnueabihf@19.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
error minimatch@10.0.1: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.20.4"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/home/bgenz-ep/Projects/bweigel/projen-weird-error/node_modules/projen/lib/task-runtime.js:147
                    throw new Error(`Task "${this.fullname}" failed when executing "${command}" (cwd: ${(0, path_1.resolve)(cwd ?? this.workdir)})`);
                    ^

Error: Task "install" failed when executing "yarn install --check-files" (cwd: /home/bgenz-ep/Projects/bweigel/projen-weird-error)
    at new RunTask (/home/bgenz-ep/Projects/bweigel/projen-weird-error/node_modules/projen/lib/task-runtime.js:147:27)
    at TaskRuntime.runTask (/home/bgenz-ep/Projects/bweigel/projen-weird-error/node_modules/projen/lib/task-runtime.js:52:9)
    at NodePackage.installDependencies (/home/bgenz-ep/Projects/bweigel/projen-weird-error/node_modules/projen/lib/javascript/node-package.js:840:17)
    at NodePackage.postSynthesize (/home/bgenz-ep/Projects/bweigel/projen-weird-error/node_modules/projen/lib/javascript/node-package.js:354:18)
    at MonorepoTsProject.synth (/home/bgenz-ep/Projects/bweigel/projen-weird-error/node_modules/projen/lib/project.js:356:22)
    at MonorepoTsProject.synth (/home/bgenz-ep/Projects/bweigel/projen-weird-error/node_modules/@aws/pdk/monorepo/projects/typescript/monorepo-ts.js:330:15)
    at evalmachine.<anonymous>:8:19
    at Script.runInContext (node:vm:133:12)
    at Object.runInContext (node:vm:281:6)
    at createProject (/home/bgenz-ep/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/projects.js:97:8)
```

### Reproduction Steps

Run `npx projen new --from @aws/pdk monorepo-ts` in a Node 18 environment.

### Possible Solution

Pin `syncpack` version to 12.3.3 (the last one not using `minimatch` >9), using the `"resolutions"` in `package.json`:

```
project.package.addPackageResolutions('syncpack@12.3.3');
```

### Additional Information/Context

_No response_

### PDK version used

0.23.48

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Manjaro Linux, NodeJS v18.20.4

### PR DESCRIPTION
**Pull request by bweigel**
fixes #823

### CODE REVIEW

**Comment by JamieMason** [comment]
👋 syncpack v13 should also work for you on Node 18, I reverted the dependency bump which required v20 https://github.com/JamieMason/syncpack/releases/tag/13.0.0

**Comment by cogwirrel** [comment]
Thanks for this! Looks like you might need to update more snapshots - can be a bit fiddly with monorepo changes as PDK dogfoods itself :)

**Comment by bweigel** [comment]
> Thanks for this! Looks like you might need to update more snapshots - can be a bit fiddly with monorepo changes as PDK dogfoods itself :)

@cogwirrel, I don't know why it still fails. I can run the `pnpm build` locally, without any issues... Well except the `rsync` is missing from the devcontainer image, but that I can install and after that it just works as expected.

**Review by cogwirrel — APPROVED** [review]

**Review by agdimech — APPROVED** [review]

**Comment by cogwirrel** [comment]
Thanks for your contribution @bweigel! 🙌

**Pull request merged**
